testbusapp/urls.py
from django.urls import path


from testbusapp.views import *
from testbusapp.forms import *
from django.conf import settings
from django.conf.urls import include,url
#from rest_framework_jwt.views import *

app_name = "testbusapp"

urlpatterns = [

    path('home/',HomeView.as_view(),name="home"),
    path('login/',LoginView.as_view(),name="login"),
    path('signup/',SignUpView.as_view(),name="signup"),
    path('logout/',LogoutView,name="logout"),
    path('about/',AboutView.as_view(),name="about"),
    path('terms/',TermsView.as_view(),name="terms"),
    path('cities/',CitiesView.as_view(),name="cities"),
    path('user_bookings/',UserBookingsView.as_view(),name="user_bookings"),
    path('user_profile/',UserProfile.as_view(),name="user_profile"),
    path('edit_profile/',EditUserProfile.as_view(),name="edit_profile"),
    path('cancel_tickets/',CancelTicketsView.as_view(),name="cancel_tickets"),
    path('cancel_tickets_confirm/',CancelTicketsConfirmedView.as_view(),name="cancel_tickets_confirm"),
    path('search_buses/',SearchBusesView.as_view(),name="search_buses_form"),
    path('search_buses/show_buses/',ShowBusesView.as_view(),name="show_buses"),
    path('search_buses/show_seats/<int:bus_id>/<str:src>/<str:dest>/<int:day>/<int:month>/<int:year>/',ShowSeatsView.as_view(),name="show_seats_of_a_bus"),
    path('seats_passengers_details/',SeatsPassengersDetailsView.as_view(),name="seats_passengers_details"),
    path('payment/',PaymentView.as_view(),name="payment"),
    path('payment_confirmed/',PaymentConfirmedView.as_view(),name="payment_confirmed"),
    path('cancellation_policy/',CancellationPolicyView.as_view(),name="cancellation_policy")
#     path('logout/',Logout_view,name="logout"),
#     path('colleges/',CollegeView.as_view(),name="college_details"),
#     path('colleges/<int:pk>/',CollegeDetailsView.as_view(),name="particular_college_details"),
#     path('colleges/addcollege/',CreateCollegeView.as_view(),name="add_college"),
#     path('colleges/<int:pk>/addstudent',AddStudentView.as_view(),name="add_student"),
#     path('colleges/<int:pk>/editcollege',EditCollegeView.as_view(),name="edit_college"),
#     path('colleges/<int:college_id>/<int:pk>/editstudent',EditStudentView.as_view(),name="edit_student"),
#     path('colleges/<int:pk>/deletecollege/',DeleteCollegeView.as_view(),name="delete_college"),
#     path('colleges/<int:college_id>/<int:pk>/deletestudent',DeleteStudentView.as_view(),name="delete_student"),
#     path('departments/',DepartmentsView.as_view(),name="college_details"),
#     # path('api/colleges_list/',colleges_list,name='college_list_json'),
#      path('api/college_details/<int:pk>/',college_details,name='college_details_json'),
#     # path('api/colleges_list/<int:pk>/students/',college_students.as_view(),name='college_students_json'),
#
# #    path('colleges_/', collegeListViewSerializer.as_view(), name="colleges_"),
#     path('colleges_/add/', CreateCollegeViewSerializer.as_view(), name="addCollege_"),
#     path('colleges_/<int:pk>/edit/', EditCollegeViewSerializer.as_view(), name="editCollege_"),
#     path('colleges_/<int:pk>/delete/', DeleteCollegeViewSerializer.as_view(), name='deleteCollege_'),
#
#     #path('colleges_/<int:pk>/', CollegeDetailsViewSerializer.as_view(), name='collegesmarks_'),
#     path('colleges_/<int:cpk>/students/<int:pk>/', StudentDetailViewSerializer.as_view(), name='studentDetails_'),
#     path('colleges_/<int:pk>/students/addstudent/', CreateStudenteViewSerializer.as_view(), name="addStudent_"),
#     path('colleges_/<int:cpk>/students/<int:pk>/editstudent/', EditStudentViewSerializer.as_view(),
#          name="editStudent_"),
#     path('colleges_/<int:cpk>/students/<int:pk>/deletestudent/', DeleteStudentViewSerializer.as_view(),
#          name="deleteStudent_"),
#
#     path('api/api-auth-token/',obtain_jwt_token)
]

testbusproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('testbusapp.urls')),
]

templates/cancel_tickets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cancellation</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
<script type="text/javascript" language="JavaScript">

    var selected_seats="";
    var selected_seats_count=0;
    function select_seat(seat_id)
    {
        element=document.getElementById(seat_id);
            if(element.style.backgroundColor=="red")
            {
                element.style.backgroundColor="white";
                if(selected_seats_count==1)
                    selected_seats=selected_seats.replace(seat_id,"");
                else
                    {
                        if(selected_seats.indexOf(seat_id)==0)
                            selected_seats=selected_seats.replace(seat_id+",","");
                        else
                            selected_seats=selected_seats.replace(","+seat_id,"");
                    }
                selected_seats_count--;
            }
            else
            {
                if(selected_seats=="")
                {
                    selected_seats=seat_id;
                }
                else
                {
                    selected_seats=selected_seats+","+seat_id;
                }
                selected_seats_count++;
                element.style.backgroundColor="red";
            }
        if(selected_seats=="")
            {
                document.getElementsByName("selected_seats_tag")[0].value="NO SEAT IS CANCELLED";
                document.getElementById("submit_tag").type="hidden";
            }
        else
            {
                document.getElementsByName("selected_seats_tag")[0].value=selected_seats;
                document.getElementById("submit_tag").type="submit";
            }
    }
</script>
<style>
    .nav-link
    {
        font-size:20px;
    }
</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<center>
    <div style="width=400;border:1px solid black;">
        <br><br>
        <table  class="table table-hover">
            <tr>
                <th>Seat ID</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Cancel</th>
            </tr>
            {% for i in booked_passengers_list %}
            <tr>
                <td>{{i.seat}}</td>
                <td>{{i.name}}</td>
                <td>{{i.age}}</td>
                <td>{{i.gender}}</td>
                <td><button id="{{i.seat}}" style="background:white;" onclick="select_seat('{{i.seat}}')">Cancel</button></td>
            </tr>
            {% endfor %}
        </table>
        <br><br>
        <form method="post" action="/cancel_tickets_confirm/">
            {% csrf_token %}
            <b>CANCEL SEATS : </b><input type="text" name="selected_seats_tag" value="NO SEAT IS CANCELLED" readonly/>
            <input type="hidden" name="ticket_id" value="{{ticket_id}}"/>
            <input type="hidden" id="submit_tag" value="Cancel"/>
        </form>
        <br><br>
    </div>
</center>
</body>
</html>

templates/cancel_tickets_confirmed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cancellation Confirmed</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
</head>
<style>
    .nav-link
    {
        font-size:20px;
    }
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<center>
<div class="card border-info mb-3" style="max-width: 30rem; border-radius:30px;">
  <div class="card-body">
      <div class="alert alert-dismissible alert-success">
        <strong>Seats -{{cancel_seats_str}} were Successfully Cancelled.</strong>
    </div>
  </div>
</div>
</center>

</body>
</html>

templates/cancellation_policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cancellation Policy</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
<style>
    .rounded_rectangle_div
    {
        max-width: 70rem;
        border-radius:30px;
        text-align:left;
    }
    .nav-link
    {
        font-size:20px;
    }
</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<center>
    <div id="user_bookings" class="card border-info mb-3" style="max-width: 80rem; border-radius:30px;float:middle;">
  <div class="card-body">
    <div class="alert alert-dismissible alert-danger" style="max-width: 70rem; border-radius:30px;">
        <h3>Cancellation Policies</h3>
    </div>
    <div class="alert alert-dismissible alert-info rounded_rectangle_div">
        <strong><li>If You have booked multiple tickets you can cancel all of them or some of them.</li></strong>
    </div>
    <div class="alert alert-dismissible alert-info rounded_rectangle_div">
        <strong><li>You Can Cancel A Ticket/s Till an Hour to Journey.</li></strong>
    </div>
    <div class="alert alert-dismissible alert-info rounded_rectangle_div">
        <strong><li>You Cannot Cancel a Ticket/s With in an hour to begin the Journey.</li></strong>
    </div>
  </div>
    </div>

<!--<div class="alert alert-dismissible alert-danger">-->
  <!--<strong></strong>-->
<!--</div>-->

<!--<div class="alert alert-dismissible alert-info">-->
  <!--<strong></strong>-->
<!--</div>-->

<!--<div class="alert alert-dismissible alert-warning">-->
    <!--<strong></strong>-->
<!--</div>-->
</center>
</body>
</html>

templates/date_of_journey_wrong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OOPS! Incorrect DOJ</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
</head>
<style>
    .nav-link
    {
        font-size:20px;
    }
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item  active">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<center>
    <div class="card border-info mb-3" style="max-width: 30rem; border-radius:30px;">
  <div class="card-body">
      <div class="alert alert-dismissible alert-danger">
          <strong><h1>Warning!!!</h1></strong>
    </div>
      <div class="alert alert-dismissible alert-danger">
          <strong>Date of Journey you have entered is incorrect.</strong>
    </div>
      <div class="alert alert-dismissible alert-danger">
          <strong>Please Enter a valid date of journey.</strong>
    </div>
      <div class="alert alert-dismissible alert-info">
          <strong><h2><u>Restrictions:</u></h2></strong>
    </div>
      <div class="alert alert-dismissible alert-info">
          <strong>1. Date of Journey must be of today's date or future.</strong>
    </div>
      <div class="alert alert-dismissible alert-info">
          <strong>2. Date of Journey can never be past.</strong>
    </div>
      <div class="alert alert-dismissible alert-info">
          <strong>3. Date of Journey should be within 6 months from today's date</strong>
    </div>
      <a href="/search_buses/"><button  class="btn btn-success" >Search Buses</button></a>
  </div>
</div>
</center>
</body>
</html>

templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit {{request.user}}'s Profile</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
</head>
<style>
    .nav-link
    {
        font-size:20px;
    }
</style>
<body>
<script type="text/javascript">
    function validateform()
    {
        var username=document.forms['user_details']['username'].value;
        var age=document.forms['user_details']['age'].value;
        var gender_select=document.forms['user_details']['gender'];
        var gender=gender_select.options[gender_select.selectedIndex].value;
        var email=document.forms['user_details']['email'].value;
        var mobile=document.forms['user_details']['mobile'].value;

        if(username=="")
            {
                alert("Enter Valid Username");
                return false;
            }
        if(age<0)
        {
            alert("Enter Valid Age");
            return false;
        }
        if(mobile>9999999999)
        {
            alert("Enter Valid Mobile Number");
            return false;
        }
        if(mobile<1000000000)
        {
            alert("Enter Valid Mobile Number");
            return false;
        }
        var re = /^(?:[a-z0-9!#$%&amp;'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$/;
        var x= re.test(email);

        if(x==false)
        {
            alert("Enter Valid Email Address");
            return false;
        }
        (document.getElementsByName("updated_user_profile")[0]).value=username+";"+String(age)+";"+String(gender)+";"+String(mobile)+";"+String(email);
        return true;
    }

</script>
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<center>
<div class="card border-info mb-3" style="max-width: 30rem; border-radius:30px;">
  <div class="card-body">
      <form name="user_details" method="post" onsubmit="return validateform()">
          {% csrf_token %}
      Username: <input name="username" type="text" value="{{username}}" size="40"/><br><br>
      Age: <input name="age" type="number" min="1" max="150" value="{{age}}" style="width:250px;"/><br><br>
      Gender: <select name="gender">
          <option value="Male">Male</option>
          <option value="Female">Female</option>
      </select>    <br><br>
      Mobile: <input name="mobile" type="number" min="1000000000" max="9999999999" value="{{mobile}}" maxlength="10" style="width:280px;"/><br><br>
      E-mail: <input name="email" type="email" value="{{email}}" size="40"/><br><br>
      <input type="hidden" name="updated_user_profile"/>
      <input type="submit" class="btn btn-primary btn-lg btn-block" value="Update Profile"/>
      </form>
  </div>
</div>
</center>
</body>
</html>

templates/show_buses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{bus_cities_times_seats_details.0.source_city.name}} to {{bus_cities_times_seats_details.0.destination_city.name}} Show Buses</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
</head>
<style>
    .nav-link
    {
        font-size:20px;
    }
</style>
<body>
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="navbar-collapse collapse show" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/home/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cities/">Cities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/terms/">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cancellation_policy/">Cancellation Policy</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/search_buses/">Search Buses</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="/login/">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/signup/">Sign Up</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/user_profile/">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/edit_profile/">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/user_bookings/">My Bookings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
{%for details in bus_cities_times_seats_details %}
<div class="card text-white bg-dark mb-3" style="max-width: 200rem;">
      <div class="card-header">
        <h6>BUS ID : {{details.bus_object.id}}</h6>
        <h6>COMPANY : {{details.bus_object.company}}</h6>
        <h6>TYPE : {{details.bus_object.bus_type}}</h6>
      </div>
        <table>
        <th>FROM</th>
        <th>TO</th>
        <th>DEPARTING TIME</th>
        <th>REACHING TIME</th>
        <th>DATE</th>
        <th>TOTAL SEATS</th>
        <th>SEATS AVAILABLE</th>
        <th>BOOK SEAT</th>
    </tr>
    <tr>
        <th>{{details.source_city.name}}</th>
        <th>{{details.destination_city.name}}</th>
        <th>{{details.source_arrival_time}}</th>
        <th>{{details.destination_reach_time}}</th>
        <th>{{date_of_journey_str}}</th>
        <th>{{details.bus_object.total_seats}}</th>
        <th>{{details.seats_available}}</th>
        <th><a href="{% url 'testbusapp:show_seats_of_a_bus' details.bus_object.id details.source_city.name details.destination_city.name date_of_journey_dict.day date_of_journey_dict.month date_of_journey_dict.year%}"><button class="btn btn-outline-success">BOOK</button></a></th>
    </tr>
    </table>
</div>
{% endfor %}
</body>
</html>